/*
 * This source file was generated by the Gradle 'init' task
 */
package com.moonlight.lib

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
    
    fun hello(s: String): String {
        return "hallo $s, selamat datang di indomaret"
    }
}
